### ISSUE TITLE
gltf-loader.js加载纹理有问题

### ISSUE THREAD

**Issue by SummerisYoung** [wechat-miniprogram/threejs-miniprogram#10]
![微信图片_20191119192739](https://user-images.githubusercontent.com/49905884/69142866-ac7dff00-0b02-11ea-8c83-87e09d17ea32.png)
如图，小程序没有window啊，这里加载会报Cannot read property 'URL' of undefined的错误，导致纹理加载不了

**Comment by geshu** [comment]
直接设定url=‘’

**Comment by ele828** [comment]
已加上 URL 的适配，可以更新版本试试。

**Comment by xiebin2015** [comment]
有URL的适配了吗？

**Comment by SummerisYoung** [comment]
> 有URL的适配了吗？

不晓得，已经没做这个了
