### ISSUE TITLE
example 在 iPhone 大屏手机上显示不了模型

### ISSUE THREAD

**Issue by liangxiaowei** [wechat-miniprogram/threejs-miniprogram#11]
你好，我在 iPhone 大屏手机上跑 example 工程一片空白，显示不了模型。同样的代码在 iPhone8 上面可以显示。能帮忙看下是什么问题吗？现在我定位到的导致出问题的地方是 canvas 的高度。下面是我测试的机型和测试步骤：

测试机型：iPhone6p/iPhone7p/iPhone X
测试步骤：
1，把 index.xml 第一个 canvas style 里面的 height 改成 456 px 就会显示不了(大于455的值都显示不了)，模拟器可以显示。
2，把 index.xml 第一个 canvas style 里面的 height 改成 455 px 就可以显示。

如果你们那边也复现出同样的问题，麻烦告知一声，谢谢🙏

**Comment by liangxiaowei** [comment]
已经解决了
![image](https://user-images.githubusercontent.com/8638403/70994882-17beef00-210a-11ea-8f2e-7d90d673ea96.png)

**Comment by mengxin-FE** [comment]
该问题依然存在，height大于455就会不显示，请问您怎么解决的呢
