### ISSUE TITLE
频繁进入模型页面微信会闪退

### ISSUE THREAD

**Issue by liangxiaowei** [wechat-miniprogram/threejs-miniprogram#12]
您好，我频繁进入模型页面微信会闪退，模型就是 demo 提供的模型，代码也是类似的比较简单，这个库使用有什么需要注意的地方吗？例如页面退出要调用什么释放内存的 api ？还是说内存问题无法解决？  
我已经上传了微信日志，微信号：liangxiaowei18，时间点：2019-12-21 上午，您这边可以帮忙查下什么原因吗？

**Comment by liangxiaowei** [comment]
您好，现在发现不显示模型，只要频繁进入页面，在 threeJS 注册 canvas，iPhone 就会闪退，而安卓没怎么闪退，这可能是什么原因？

**Comment by ele828** [comment]
这个可能跟 WebGL 内存泄露有关，我们在下一个版本已经修复了这个问题。

**Comment by liangxiaowei** [comment]
你好请问 2.10.0 这个版本修复了吗？还是说 2.10.0 的下个版本？
