### ISSUE TITLE
是否支持VideoTexture

### ISSUE THREAD

**Issue by 2H0U** [wechat-miniprogram/threejs-miniprogram#13]
实际运行没有报错，但是效果不对：并没有播放视频，而是使物体消失或透明了。

**Comment by ele828** [comment]
这个会支持，可以关注近期的更新。

**Comment by ItsRyanWu** [comment]
@ele828 请问已经支持了吗？该如何使用？我试了通过 createSelectorQuery 获取 video 节点传入 VideoTexture( video ) 但是结果并无法成功渲染
