### ISSUE TITLE
多级页面,在安卓机型上,多次来回进入退出会导致崩溃

### ISSUE THREAD

**Issue by wamich** [wechat-miniprogram/threejs-miniprogram#16]
**代码说明**

代码片段共2个页面,有首页(index/index)和测试页(three/index).

**问题安卓机型**

mate 20 pro, oppo r11, pixel 3, 等

**复现路径**

从首页进入测试页,再从测试页返回首页,如此反复多次(有些3次,有些7,8次,还有10多次),会出现小程序闪退.

目前代码片段里已经加入内存释放功能,但是依然每次进入都会内存增加多,释放少,导致越来越多.即使加入内存警告,大部分情况下,没有警告,就直接闪退.

**代码片段**
https://developers.weixin.qq.com/s/Ps7EDJm87ygO

**Comment by wamich** [comment]
是安卓微信的版本bug？还是这个库的问题？

**Comment by wamich** [comment]
@ele828 帮忙看下？代码片段就是在example里的内容，增加了一点dispose而已。

**Comment by wamich** [comment]
再来催下

**Comment by ele828** [comment]
我们这边看下

**Comment by cailven** [comment]
同样发现这个问题

**Comment by wamich** [comment]
> 我们这边看下

亲，可以解决吗？

**Comment by ele828** [comment]
已经修复了，可以试试内测版 https://developers.weixin.qq.com/community/develop/doc/000ee26694485043166aa51bd51c01?blockType=1
