### ISSUE TITLE
鼠标事件响应怎么实现？

### ISSUE THREAD

**Issue by linyanghuan** [wechat-miniprogram/threejs-miniprogram#19]
1. 插件有实现鼠标事件响应吗？还是需要自己手动添加？
2. 我包装好OrbitControls引入到项目里，但没有反应，是不是由于没有引入事件导致的？
3. 有没相应的使用示例？

**Comment by ele828** [comment]
touch 事件目前确实不支持，我们做一下适配

**Comment by ele828** [comment]
已经加上了
