### ISSUE TITLE
TextureLoader真机加载图片失败

### ISSUE THREAD

**Issue by geshu** [wechat-miniprogram/threejs-miniprogram#2]
试用了一下午先用的GLTFLoader开发者工具上使用成功在真机上加载出错，因为GLTF里有很多其他加载器看源码才发现是TextureLoader加载失败，然后同样的直接用TextureLoader在开发者工具中可以在但是在真机上会加载失败。
`  THREE = createScopedThreejs(canvas)

    var texture = new THREE.TextureLoader().load(
      'https://zugou.vip/aa.jpg',
      function(texture) {
        console.log('加载成功')
      },
      undefined,
      function(err) {
        console.log('加载失败')
      }
    );`
![企业微信截图_15680210257369](https://user-images.githubusercontent.com/20235873/64519455-b925f000-d326-11e9-8ed3-2cf767e7c36b.png)

因为通过npm下载过来的是build后的代码所以不好查看原因。但是感觉问题出在textureloader中使用的imageloader出现了问题。

**Comment by ele828** [comment]
我上传了一份 gltf laoder 的示例代码，你可以看下在你手机上能不能运行 https://github.com/wechat-miniprogram/threejs-miniprogram/blob/master/example/test-cases/model.js

**Comment by ele828** [comment]
我上传了一份 gltf loader 的示例代码，你可以看下在你手机上能不能运行 https://github.com/wechat-miniprogram/threejs-miniprogram/blob/master/example/test-cases/model.js

**Comment by ele828** [comment]
另外确认下开发者工具上的域名校验是否关闭了

**Comment by geshu** [comment]
您好我尝试您发的东西并且确定域名校验已经关闭但还是出现问题 我把安卓和ios的报错截屏下来
![企业微信截图_156808620522](https://user-images.githubusercontent.com/20235873/64581924-7e6f9680-d3be-11e9-84d0-823af0afb40c.png)
![企业微信截图_15680862219249](https://user-images.githubusercontent.com/20235873/64581925-7fa0c380-d3be-11e9-8962-a18814e22b12.png)
这个报错和我当初自己尝试时的报错是一致的，当初在看过源码后发现问题处在textureloader上。因为gltf是一个合成文件，它里面有多个信息，比如scene camera light 模型 贴图等，所以会用到其他的loader，而这个报错是在调用textureloader时出错，textureloader会去调用imageloaer，但是textureloader和imageloader是写在threejs的主体文件里的，使用您的方法后threejs的主体文件是build后的就导致我找不到具体的位置修改。在微信开发社区里已经有人通过修改iamgeloader来实现真机加载贴图，https://developers.weixin.qq.com/community/develop/article/doc/0006eedd21caf84e80985bfb95b813
但我在使用其方式时有些时候也会出写图片加载不出来，所以我也不能确定这imagloader的问题出在什么地方。终归问题是出现imageloader上。

**Comment by geshu** [comment]
忘了说的是在使用GFTFLoader时会有些其他的报错如URL=Window.URL这种微信不支持的方法调用但是能修改就没有提出来

**Comment by geshu** [comment]
问题已经解决。还是使用了canvas.createImage的方法来修改imageloader，写了一个Texture&ImageLoader来覆盖了原来的Texture&ImageLoader

**Comment by sanyuered** [comment]
@geshu 

1、我提供一个思路。微信开发者工具的”不校验合法域名“这个功能，在真机上并不管用。

2、我观察的现象：
微信开发者工具正常加载一个无贴图的.glb，并设置了不校验合法域名，而真机不能加载。
如果真机打开小程序调试模式，则真机能加载。
如果在小程序网站的开发者配置增加该.glb地址的合法域名，则真机能加载。
至于有贴图的.glb，因为小程序不支持URL.createObjectURL()方法，所以不能加载。

3、对于有贴图的.gltf，您通过修改imageloader来实现加载，也是一个思路。我在微信小程序网站配置合法域名后，有贴图的.gltf暂时没有出现不能加载的现象。

示例：https://github.com/sanyuered/WeChat-MiniProgram-AR-3D/blob/master/package_3d_viewer/pages/camera/camera.js
`
// a glb model url
//const modelUrl = 'https://sanyuered.github.io/gltf/robot.glb';
// a gltf model url
const modelUrl = 'https://sanyuered.github.io/gltf/cube/scene.gltf';
`

**Comment by Primary-Traxex** [comment]
> @geshu
> 
> 1、我提供一个思路。微信开发者工具的”不校验合法域名“这个功能，在真机上并不管用。
> 
> 2、我观察的现象：
> 微信开发者工具正常加载一个无贴图的.glb，并设置了不校验合法域名，而真机不能加载。
> 如果真机打开小程序调试模式，则真机能加载。
> 如果在小程序网站的开发者配置增加该.glb地址的合法域名，则真机能加载。
> 至于有贴图的.glb，因为小程序不支持URL.createObjectURL()方法，所以不能加载。
> 
> 3、对于有贴图的.gltf，您通过修改imageloader来实现加载，也是一个思路。我在微信小程序网站配置合法域名后，有贴图的.gltf暂时没有出现不能加载的现象。
> 
> 示例：https://github.com/sanyuered/WeChat-MiniProgram-AR-3D/blob/master/package_3d_viewer/pages/camera/camera.js
> `
> // a glb model url
> //const modelUrl = 'https://sanyuered.github.io/gltf/robot.glb';
> // a gltf model url
> const modelUrl = 'https://sanyuered.github.io/gltf/cube/scene.gltf';
> 
> `

如果是经过压缩的glb文件呢, 我看three.js官方做法是要加DRACOLoader.js插件解压的, 但是移植到小程序会遇到不支持URL.createObjectURL的问题

**Comment by sanyuered** [comment]
> 如果是经过压缩的glb文件呢, 我看three.js官方做法是要加DRACOLoader.js插件解压的, 但是移植到小程序会遇到不支持URL.createObjectURL的问题

1、glb是gltf的普通二进制格式，DRACOLoader.js压缩后的格式虽然也是glb，但前者只用GLTFloader.js可以加载，后者需要DRACOLoader.js解压缩。
2、提示不支持URL.createObjectURL的原因是：glb中包含纹理图像，小程序为纹理图像创建window.URL对象失败。

**Comment by SunXinFei** [comment]
> 问题已经解决。还是使用了canvas.createImage的方法来修改imageloader，写了一个Texture&ImageLoader来覆盖了原来的Texture&ImageLoader

@geshu 求解
