### ISSUE TITLE
<canvas>type无法指定为'2d'

### ISSUE THREAD

**Issue by zhangrunhao** [wechat-miniprogram/threejs-miniprogram#24]
1. 需要在原声组件上, 覆盖<cover-view>
2. 如果type指定为'webgl'的话, `<cover-view>`组件无法显示
3. 如果type指定为'2d', threejs无法正常渲染.

**Comment by ele828** [comment]
2d 运行不了three.js 的。webgl 同层会在近期支持上。

**Comment by zhangrunhao** [comment]
@ele828 老板, 近期有具体的计划吗?

**Comment by zhangrunhao** [comment]
@ele828 您好, 是否方便告知近期的大概时间范围呢. 非常期待. 感谢大佬
