### ISSUE TITLE
canvas高度设置为460px或更大时，不能显示

### ISSUE THREAD

**Issue by lotusr039** [wechat-miniprogram/threejs-miniprogram#3]
具体来说是在苹果手机上显示白屏，安卓手机显示黑屏，log无异常信息

当高度改为450px以下显示就正常

**Comment by sanyuered** [comment]
1、微信官方《bug: 避免设置过大的宽高，在安卓下会有crash的问题》
https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html

2、每个手机屏幕的高度各不一样，如果是为全屏幕显示，一般做法是设置canvas的高度为100%。
