### ISSUE TITLE
在小程序中创建VideoTexture的问题

### ISSUE THREAD

**Issue by tommyfok** [wechat-miniprogram/threejs-miniprogram#30]
通过`THREE.VideoTexture`方法创建视频贴图，应该传入什么值？我试过视频的url、VideoContext都不行，求解！

**Comment by ele828** [comment]
可以借助 canvas 2d 的 drawImage 绘制 videoContext 之后再传递给 three.js

**Comment by tommyfok** [comment]
drawImage传入VideoContext之后报了这样的错
![image](https://user-images.githubusercontent.com/3250229/90500180-1c4a1480-e17d-11ea-8423-36360a351dd6.png)
