### ISSUE TITLE
v0.0.6 npm包不能build npm

### ISSUE THREAD

**Issue by yuedou** [wechat-miniprogram/threejs-miniprogram#38]
npm install threejs-miniprogram@0.0.6 下载下来的包缺失dist 目录

**Comment by deepkolos** [comment]
可以试试 https://github.com/deepkolos/three-platformize

**Comment by mengxin-FE** [comment]
麻烦请尽量解决这个问题吧， https://github.com/deepkolos/three-platformize 这个也有问题

**Comment by deepkolos** [comment]
@mengxin-FE 额 deepkolos/three-platformize 不依赖threejs-miniprogram，npm包里面也有build、src、examples文件夹，怎么就也有这个问题呢？

**Comment by mengxin-FE** [comment]
> @mengxin-FE 额 deepkolos/three-platformize 不依赖threejs-miniprogram，npm包里面也有build、src、examples文件夹，怎么就也有这个问题呢？

提了issue ，npm run bulid 有报错，node_modules里面three-platformize-demo缺了好几个ts文件

**Comment by xzq2325** [comment]
我这边也是build之后构建npm，编译完就报错了。VM693 WAService.js:2 TypeError: (void 0) is not a function

**Comment by Tidyzq** [comment]
fixed in 0.0.8
