### ISSUE TITLE
怎么给小程序里面添加orbitcontrols

### ISSUE THREAD

**Issue by wh123660** [wechat-miniprogram/threejs-miniprogram#4]

**Comment by wh123660** [comment]
希望能把控制器也弄下，这样就会好用了

**Comment by HolyShitKillingMachine** [comment]
关于控制，我还是用的小程序本身的Bindtouch和bindtouchmove，然后自己写模型控制

**Comment by wh123660** [comment]
好吧，看来只能这样了

**Comment by sanyuered** [comment]
https://github.com/sanyuered/WeChat-MiniProgram-AR-3D

微信小程序显示gltf模型，支持用手势事件和手机传感器控制3D旋转，供参考。

**Comment by ele828** [comment]
@wh123660 你可以 orbitcontrols 的，只需要稍微做一下适配，然后类似这样包一下 https://github.com/wechat-miniprogram/threejs-miniprogram/blob/b0f651b3430141d362b808b90cbdb1020a371fdf/example/loaders/gltf-loader.js#L1
