### ISSUE TITLE
0.0.6版本构建后无法运行

### ISSUE THREAD

**Issue by RMiTiG** [wechat-miniprogram/threejs-miniprogram#42]
下载最新代码（0.0.6版本），install和build都正常，成功生成dist/index.js，但是在小程序import后调用createScopedThreejs报错：
thirdScriptError
(void 0) is not a function

改成0.0.5版本可以正常运行，查看提交记录在index,js的createScopedThreejs添加了行HTMLCanvasElement = undefined，把该行注释掉0.0.6才可以正常运行

**Comment by deepkolos** [comment]
可以尝试下 https://github.com/deepkolos/three-platformize

**Comment by Tidyzq** [comment]
fixed
