### ISSUE TITLE
模拟器可以，真机显示不出来～～～

### ISSUE THREAD

**Issue by whousedmine** [wechat-miniprogram/threejs-miniprogram#8]

**Comment by sanyuered** [comment]
1、是真机显示不出来gltf模型吗？
如果是，则需要做一下设置。

2、有2种配置：
第1种：用微信开发者工具发布到手机上，点击小程序的右上角按钮，打开小程序的调试模式。
第2种：在微信小程序开发者配置界面，将gltf模型的地址添加到request合法域名。

3、微信小程序显示gltf模型，并支持手势和传感器旋转模型。
https://github.com/sanyuered/WeChat-MiniProgram-AR-3D

**Comment by ele828** [comment]
可以提供一下代码片段看看

**Comment by ele828** [comment]
已修复

**Comment by jtrhb** [comment]
shader在模拟器上可以显示，真机显示不出来，请教是什么问题
