### ISSUE TITLE
大模型在真机上报错

### ISSUE THREAD

**Issue by yiwuxing** [wechat-miniprogram/threejs-miniprogram#9]
如题，使用threejs-miniprogram的过程中，展示比较小的模型时在开发者工具和真机上都能正常显示，展示大的模型时，在开发者工具上正常显示，在真机上报错，报错如图所示
![miniprog-threejs](https://user-images.githubusercontent.com/26779894/68859966-77009c80-0723-11ea-8bc6-d37809ea7ff1.jpeg)

**Comment by yiwuxing** [comment]
![miniprog-threejs](https://user-images.githubusercontent.com/26779894/68859934-60f2dc00-0723-11ea-8fec-b54d77e3dea5.jpeg)

**Comment by ele828** [comment]
模型具体有多大呢？

**Comment by ele828** [comment]
这个看起来是网络请求的问题，跟 three.js 可能无关，这个Issue先关闭了。如果问题还存在建议到开发者社区反馈。
